name: authorization-service

services:
  authorization-cache:
    image: redis:7-alpine
    container_name: authorization-cache
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - auth-redis-data:/data
    networks:
      - auth-network
volumes:
  auth-db-data:
  auth-redis-data:
networks:
  auth-network:
    driver: bridge
