root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd"
bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "sql"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]
delay = 1000 # Giữ lại delay 1s của bạn

[build.windows]
cmd = "go build -o ./tmp/main.exe ./cmd"
bin = "main.exe"

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true # Bật time lên cho dễ debug

[misc]
clean_on_exit = false